apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-2
data:
  index.html: |
    <html>
    <head>
    THRSNKNWLDGTHTSNTPWR
    </head>
    <body>
    <b>-- Custom index page --</b>
    </body>
    </html>